parameters:
  EnvVars: {}
  InjectedPackages: ''

stages:
  - template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      AllocateResourceGroup: 'false'
      JobName: Test_Blob
      ServiceDirectory: storage
      EnvVars: ${{ parameters.EnvVars }}
      InjectedPackages: ${{ parameters.InjectedPackages }}
      Transform: |
        $_.parameters["BuildTargetingString"] = "azure-storage-blob"

  - template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      AllocateResourceGroup: 'false'
      JobName: Test_Blob_ChangeFeed
      ServiceDirectory: storage
      EnvVars: ${{ parameters.EnvVars }}
      InjectedPackages: ${{ parameters.InjectedPackages }}
      Transform: |
        $_.parameters["BuildTargetingString"] = "azure-storage-blob-changefeed"

  - template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      AllocateResourceGroup: 'false'
      JobName: Test_Queue
      ServiceDirectory: storage
      EnvVars: ${{ parameters.EnvVars }}
      InjectedPackages: ${{ parameters.InjectedPackages }}
      Transform: |
        $_.parameters["BuildTargetingString"] = "azure-storage-queue"

  - template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      AllocateResourceGroup: 'false'
      MaxParallel: 1
      JobName: Test_Datalake
      ServiceDirectory: storage
      EnvVars: ${{ parameters.EnvVars }}
      InjectedPackages: ${{ parameters.InjectedPackages }}
      Transform: |
        $_.parameters["BuildTargetingString"] = "azure-storage-file-datalake"

  - template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      AllocateResourceGroup: 'false'
      JobName: Test_FileShares
      ServiceDirectory: storage
      EnvVars: ${{ parameters.EnvVars }}
      InjectedPackages: ${{ parameters.InjectedPackages }}
      Transform: |
        $_.parameters["BuildTargetingString"] = "azure-storage-file-share"
