parameters:
  - name: ServiceDirectory
    type: string
    default: ''
  - name: EnvVars
    type: object
    default: {}
  - name: MaxParallel
    type: number
    default: 0
  - name: BeforeTestSteps
    type: object
    default: []
  - name: AfterTestSteps
    type: object
    default: []
  - name: BuildTargetingString
    type: string
    default: 'azure-*'
  - name: AdditionalTestArgs
    type: string
    default: ''
  - name: TestMarkArgument
    type: string
    default: ''
  - name: InjectedPackages
    type: string
    default: ''
  - name: BuildDocs
    type: boolean
    default: true
  - name: JobName
    type: string
    default: 'Test'
  - name: AllocateResourceGroup
    type: boolean
    default: true
  - name: DeployArmTemplate
    type: boolean
    default: false
  - name: TestTimeoutInMinutes
    type: number
    default: 120
  - name: TestSamples
    type: boolean
    default: false
  - name: Location
    type: string
    default: ''
  - name: MatrixConfigs
    type: object
    default:
      - Name: Python_live_test_base
        Path: eng/pipelines/templates/stages/platform-matrix.json
        Selection: sparse
        GenerateVMJobs: true
  - name: AdditionalMatrixConfigs
    type: object
    default: []
  - name: MatrixFilters
    type: object
    default: []
  - name: PlatformPreSteps
    type: object
    default: []
  - name: PlatformPostSteps
    type: object
    default: []

stages:
  - stage: Live_${{ parameters.JobName }}
    jobs:
    - template: ../jobs/archetype-sdk-tests.yml
      parameters:
        ServiceDirectory: ${{ parameters.ServiceDirectory }}
        EnvVars: ${{ parameters.EnvVars }}
        MaxParallel: ${{ parameters.MaxParallel }}
        BeforeTestSteps: ${{ parameters.BeforeTestSteps }}
        AfterTestSteps: ${{ parameters.AfterTestSteps }}
        AdditionalTestArgs: ${{ parameters.AdditionalTestArgs }}
        BuildTargetingString: ${{ parameters.BuildTargetingString }}
        TestMarkArgument: ${{ parameters.TestMarkArgument }}
        InjectedPackages: ${{ parameters.InjectedPackages }}
        BuildDocs: ${{ parameters.BuildDocs }}
        JobName: ${{ parameters.JobName }}
        AllocateResourceGroup: ${{ parameters.AllocateResourceGroup }}
        DeployArmTemplate: ${{ parameters.DeployArmTemplate }}
        TestTimeoutInMinutes: ${{ parameters.TestTimeoutInMinutes }}
        TestSamples: ${{ parameters.TestSamples }}
        Location: ${{ parameters.Location }}
        Matrix: ${{ parameters.Matrix }}
        CloudConfigurations: ${{ parameters.CloudConfigurations }}


  - stage: Publish_Coverage_${{ parameters.JobName }}
    jobs:
    - template: ../jobs/publish-coverage.yml
      parameters:
        ServiceDirectory: ${{ parameters.ServiceDirectory }}
